### ISSUE TITLE
A.3.14.1300. - Bulk Record Delete

### ISSUE THREAD

**Issue by mmcev106** [4bbakers/redcap_rsvc#145]
Feature: [A.3.14.1300. - Bulk Record Delete](https://github.com/4bbakers/redcap_rsvc/tree/v14.7.0/./Feature%20Tests/A/Direct%20Data%20Entry%20-%20Data%20Collection%20Instrument_14/A.3.14.1300.%20-%20Bulk%20Record%20Delete.feature)

**Comment by 4bbakers** [comment]
This one became B.3.32.0200. User Interface: The system shall support Bulk Delete functionality, allowing users to delete entire records or instrument-level data for multiple records within the Bulk Delete interface.
