### ISSUE TITLE
A.2.3.0400. - Assign Administrators and Account Managers

### ISSUE THREAD

**Issue by aldefouw** [4bbakers/redcap_rsvc#21]
Feature: [A.2.3.0400. - Assign Administrators and Account Managers](https://github.com/4bbakers/redcap_rsvc/tree/v14.7.0/./Feature%20Tests/A/Assign%20Administrators_3/A.2.3.0400.%20-%20Assign%20Administrators%20and%20Account%20Managers.feature)

**Comment by mmcev106** [comment]
@MintooXavier, I was curious why you moved this to `Discussion or Manual Review`.  I ran it on my local and it seems to be passing.  Is it done from your perspective, or did you have any concerns about it?

**Comment by MintooXavier** [comment]
@mmcev106 : I think i put it in the wrong bucket.. apologies.

**Comment by mmcev106** [comment]
@MintooXavier, I ran it on my local and it seems to be passing. Is it done from your perspective, or did you have any concerns about it?

**Comment by MintooXavier** [comment]
It's done.. It is passing.. I think I put it in the wrong bucket `Discussion or Manual Review`.. It needs to be in the `Done` list
