### ISSUE TITLE
A.3.24.1000. - eConsent IP address

### ISSUE THREAD

**Issue by aldefouw** [4bbakers/redcap_rsvc#23]
Feature: [A.3.24.1000. - eConsent IP address](https://github.com/4bbakers/redcap_rsvc/tree/v14.7.0/./Feature%20Tests/A/e-Consent%20framework_24/A.3.24.1000.%20-%20eConsent%20IP%20address.feature)

**Comment by aldefouw** [comment]
Note to @ellisthomas  and @mmcev106:

I suspect that this test is going to fail because we're not using a `Test_Admin` account (using Test_User1).

https://github.com/4bbakers/redcap_rsvc/blob/v14.7.0/Feature%20Tests/A/e-Consent%20framework_24/A.3.24.1000.%20-%20eConsent%20IP%20address.feature#L6-L17

![Image](https://github.com/user-attachments/assets/3ebf557d-dff9-4fa7-a5b5-9769b3b133a7)

You might want to verify with Theresa Baker whether it would be okay to move to Test_Admin account ... I suspect it would be fine since this is a Control Center focused test.

If we need to keep it under `Test_User1`, you'll need to add a prerequisite section like this feature has before the beginning:

https://github.com/4bbakers/redcap_rsvc/blob/v14.7.0/Feature%20Tests/B/Direct%20Data%20Entry%20-%20Data%20Collection%20Instrument_14/B.3.14.0200.%20-%20Field%20Type%20Data%20Entry.feature#L6-L15

```
    #ATS prerequisite: Normal users cannot move projects to production by default - let's adjust that before we proceed.
    Given I login to REDCap with the user "Test_Admin"
    When I click on the link labeled "Control Center"
    And I click on the link labeled "User Settings"
    Then I should see "System-level User Settings"
    Given I select "Yes, normal users can move projects to production" on the dropdown field labeled "Allow normal users to move projects to production?"
    When I click on the button labeled "Save Changes"
    And I see "Your system configuration values have now been changed!"
    Then I logout
```

**Comment by mmcev106** [comment]
@aldefouw, yes.  @ellisthomas, actually already switched this to use the admin user in #163.  If you're looking for more work, it might make sense to look at the [things assigned to you](https://github.com/orgs/vanderbilt-redcap/projects/2/views/1?filterQuery=+assignee%3Aaldefouw) or unassigned tasks.  I think everybody is actively looking into the things assigned and often already has fixes in the works (even if they haven't committed or commented about them yet).

**Comment by aldefouw** [comment]
Thanks @mmcev106.  Not looking for work per se I just happened to notice this by accident and didn't want anyone blocked 😃
