### ISSUE TITLE
B.2.10.0200. - Add Remove Users

### ISSUE THREAD

**Issue by aldefouw** [4bbakers/redcap_rsvc#30]
Feature: [B.2.10.0200. - Add Remove Users](https://github.com/4bbakers/redcap_rsvc/tree/v14.7.0/./Feature%20Tests/B/Data%20Access%20Groups_10/B.2.10.0200.%20-%20Add%20Remove%20Users.feature)

**Comment by alewis64** [comment]
Test

**Comment by alewis64** [comment]
@mmcev106 this one seemed to pass. 
![Image](https://github.com/user-attachments/assets/db9e567f-6bad-4615-98e7-f73dd7672caa)

**Comment by mmcev106** [comment]
This works consistently on Adam's computer but consistently fails for me on the first `And I should see a table header and rows containing the following values in a table` line.  Perhaps a subtle timing issue with our tooling on that step definition?  I'll assign it to myself to investigate further.

**Comment by aldefouw** [comment]
@mmcev106 - I can dig into this tomorrow afternoon if you'd like.

Otherwise, a few common things to check:

1) Make sure you're on same RCTF version
2) Do your user tables align in that REDCap table that is displaying the users?

If your user tables are not aligning, that's a good indication that your[ import files](https://github.com/4bbakers/redcap_rsvc/blob/v14.7.0/Feature%20Tests/B/Data%20Access%20Groups_10/B.2.10.0200.%20-%20Add%20Remove%20Users.feature#L18) are not the same - `import_files/user list for project 1.csv` 

If so, maybe you need to resync the redcap_rsvc repository?

**Comment by mmcev106** [comment]
@aldefouw, I was planning on bumping this to the end of my list and focusing on lower hanging fruit for now.  With that said, I'll go ahead and add more details if you're curious.

- Adam L have identical local setups to my knowledge, both running the version of rctf included in the latest version of redcap_cypress
- The users are visible (see screenshots).  I'm not sure why the `And I should see a table header and rows containing the following values in a table` step finding them.

![image](https://github.com/user-attachments/assets/9894f171-9205-4297-a2c0-b9d44e1cceec)
![image](https://github.com/user-attachments/assets/cd736df8-1ed9-42b7-a9f8-d0eebf564f14)

**Comment by aldefouw** [comment]
@mmcev106
https://github.com/4bbakers/redcap_rsvc/blob/v14.7.0/Feature%20Tests/B/Data%20Access%20Groups_10/B.2.10.0200.%20-%20Add%20Remove%20Users.feature#L20-L25

This step of the feature is going to fail until I make an update to RCTF table traversal.  

There is a problem where the table headers match:

**1) Top-stacked layer table in the dialog box** (this is the one we are trying to target)
![Image](https://github.com/user-attachments/assets/2d90dad0-3545-4d3c-ae87-8edba8549a8b)
 

**2) User RIghts table behind the dialog box**
![Image](https://github.com/user-attachments/assets/fd12561e-991d-4277-ac8f-bb2a33a7e1f6)


This happens because they both contain the word "username" in the table and we do a case-insensitive search to determine the table header indexes to match against the proper cells in the rows.

This is a framework code issue.

I have some ideas to prevent this issue from happening but wanted to let you know so that you don't waste time trying to troubleshoot at the Gherkin level.  This appears to be the only reason this feature is not working at the moment.

**Comment by mmcev106** [comment]
@aldefouw, I'm assigning you as well since either of us could look into this.  No worries if you don't get to it.  I will eventually, I've just been trying to focus on the lowest hanging fruit first.

**Comment by aldefouw** [comment]
@mmcev106  - See https://github.com/4bbakers/redcap_rsvc/pull/164

I fixed this issue for a few of the features.
