### ISSUE TITLE
B.2.10.0300. - Multiple DAGs

### ISSUE THREAD

**Issue by aldefouw** [4bbakers/redcap_rsvc#31]
Feature: [B.2.10.0300. - Multiple DAGs](https://github.com/4bbakers/redcap_rsvc/tree/v14.7.0/./Feature%20Tests/B/Data%20Access%20Groups_10/B.2.10.0300.%20-%20Multiple%20DAGs.feature)

**Comment by MintooXavier** [comment]
automated
