### ISSUE TITLE
B.2.10.0400. - User and Record Restrictions

### ISSUE THREAD

**Issue by aldefouw** [4bbakers/redcap_rsvc#32]
Feature: [B.2.10.0400. - User and Record Restrictions](https://github.com/4bbakers/redcap_rsvc/tree/v14.7.0/./Feature%20Tests/B/Data%20Access%20Groups_10/B.2.10.0400.%20-%20User%20and%20Record%20Restrictions.feature)

**Comment by MintooXavier** [comment]
This script doesn't work manually. The instrument Consent is not an e-consent, it's not even a survey.

**Comment by mmcev106** [comment]
Thanks @MintooXavier!  I'm looking into it.

**Comment by mmcev106** [comment]
@MintooXavier, I believe [this PR](https://github.com/4bbakers/redcap_rsvc/pull/143) should have fixed this. May I recruit you to merge the latest from 4bbakes/v14.7.0 into whichever branch you're working from and try again?

**Comment by aldefouw** [comment]
@mmcev106 and @MintooXavier 
https://github.com/4bbakers/redcap_rsvc/blob/v14.7.0/Feature%20Tests/B/Data%20Access%20Groups_10/B.2.10.0400.%20-%20User%20and%20Record%20Restrictions.feature#L26-L32

This step of the feature is going to fail until I make an update to RCTF table traversal.  

There is a problem where the table headers match:

**1) Top-stacked layer table in the dialog box** (this is the one we are trying to target)
![Image](https://github.com/user-attachments/assets/2d90dad0-3545-4d3c-ae87-8edba8549a8b)
 

**2) User RIghts table behind the dialog box**
![Image](https://github.com/user-attachments/assets/fd12561e-991d-4277-ac8f-bb2a33a7e1f6)


This happens because they both contain the word "username" in the table and we do a case-insensitive search to determine the table header indexes to match against the proper cells in the rows.

This is a framework code issue.

I have some ideas to prevent this issue from happening but wanted to let you know so that you don't waste time trying to troubleshoot at the Gherkin level.  This appears to be the only reason this feature is not working at the moment.

**Comment by MintooXavier** [comment]
@aldefouw : it works if we specify as below:

And I should see a table header and rows containing the following values in a table in the dialog box:

**Comment by MintooXavier** [comment]
- Added steps to enable "Consent" as e-consent. New step definition added in mintoo.js:
  https://github.com/CCTC-team/redcap_cypress/blob/MX_v14.7.0/cypress/support/step_definitions/mintoo.js
- Added steps to verify user cannot access records in another DAG

**Comment by aldefouw** [comment]
@MintooXavier - Great point in terms of recognizing that we have a way to narrow the selectors so that the table traversal code works as is!  I'll still go back to the RCTF library to fix that issue though since it creates quite a lot of confusion when developing the features which can slow down progress.

Regarding the additional step:
https://github.com/CCTC-team/redcap_cypress/blob/MX_v14.7.0/cypress/support/step_definitions/mintoo.js

Thanks for the efforts - I'm guessing you created the step because there is no label on it.  

I think we need to broadly consider how to handle the case of an inline dropdown label (meaning it exists inside the dropdown menu itself instead of as a label) rather than creating a step that only works for eConsent.

![Screenshot 2024-12-05 at 8 55 24 AM](https://github.com/user-attachments/assets/87eab2a9-32c0-469d-8b3e-f5146da14de4)

I think we can probably punt on that for now and decide later. 

Project_1.xml, which seeds the project in [this step](https://github.com/4bbakers/redcap_rsvc/blob/v14.7.0/Feature%20Tests/B/Data%20Access%20Groups_10/B.2.10.0400.%20-%20User%20and%20Record%20Restrictions.feature#L13) , was updated 2 weeks ago.

**Updated Project_1.xml enables "Consent" instrument:**
https://github.com/4bbakers/redcap_rsvc/commit/ff30943cc80295c8d3b5a5799b1a7ebd75dcd2fc
