### ISSUE TITLE
B.3.14.0100. - Create Record

### ISSUE THREAD

**Issue by aldefouw** [4bbakers/redcap_rsvc#34]
Feature: [B.3.14.0100. - Create Record](https://github.com/4bbakers/redcap_rsvc/tree/v14.7.0/./Feature%20Tests/B/Direct%20Data%20Entry%20-%20Data%20Collection%20Instrument_14/B.3.14.0100.%20-%20Create%20Record.feature)

**Comment by MintooXavier** [comment]
automated

**Comment by MintooXavier** [comment]
I have reviewed the script again to ensure it meets the URS. I believe the "create record" functionality should be tested with a non-admin user, as test_admin has elevated privileges. To facilitate this, I created two users: test_user1 with create access and test_user2 without create access. I have verified both create and edit access for each user.
