### ISSUE TITLE
B.3.15.1000. - Survey Participant List

### ISSUE THREAD

**Issue by aldefouw** [4bbakers/redcap_rsvc#36]
Feature: [B.3.15.1000. - Survey Participant List](https://github.com/4bbakers/redcap_rsvc/tree/v14.7.0/./Feature%20Tests/B/Direct%20Data%20Entry%20-%20Survey_15/B.3.15.1000.%20-%20Survey%20Participant%20List.feature)

**Comment by mmcev106** [comment]
@aldefouw, for this test cypress seems to be crashing for @alewis64 & I both at the step in the screenshot (not sure how relevant that is).   The page content in the browser window becomes totally frozen (can't click the stop button).  Refreshing the browser hangs.  Restarting cypress from the command is required to bring it back.  Do you know why this might be happening?
![Image](https://github.com/user-attachments/assets/088fe360-409a-4728-b12a-24eb8a9f1e6a)

**Comment by alewis64** [comment]
To be honest with you this may be the first test that is validating using the dropdown field in the survey distribution tools. Maybe there is no step definition for this (I hope I am using that term correctly).

Then I should see the dropdown field labeled "belonging to" with the options below
      | [Initial survey] "Text Validation" - Event 1 (Arm 1: Arm 1) |
      | "Consent" - Event 1 (Arm 1: Arm 1)                          |
      | "Text Validation" - Event 2 (Arm 1: Arm 1)                  |
      | "Survey" - Event Three (Arm 1: Arm 1)                       |
      | "Consent" - Event Three (Arm 1: Arm 1)                      |

**Comment by mmcev106** [comment]
@alewis64, it failed on a different step for me (see screenshot).  Is it consistently failing on the dropdown step for you?

**Comment by alewis64** [comment]
@mmcev106 yes it fails here every time. I can change it to something like the below and it processes as expected, until it get down to the second time we need to look at that dropdown.

Then I should see the dropdown field labeled "belonging to" with the option '[Initial survey] "Text Validation" - Event 1 (Arm 1: Arm 1)' selected
    
    And I should see a table header and rows containing the following values in a table:
      | Email             | Record | Participant Identifier | Responded | Invitation Scheduled? | Invitation Sent ? | Link   | Survey Access Code |
      | [No email listed] |        | Disabled               | [icon]    | -                     | [icon]            | [icon] | [icon]             |
      | [No email listed] |        | Disabled               | [icon]    | -                     | [icon]            | [icon] | [icon]             |
      | email@test.edu    | 1      | Disabled               | [icon]    | -                     | [icon]            | [icon] | [icon]             |
      | email@test.edu    | 2      | Disabled               | [icon]    | -                     | [icon]            | [icon] | [icon]             |

**Comment by aldefouw** [comment]
@mmcev106 & @alewis64  - These issues are on my radar.  Hoping to review today.  I've been asked to prioritize a resume review process for another manager in my service line so that is my first priority.

I can verify on my machine to know for sure later today, but your screenshot gives some clues.

Here's my guess: I think this is probably happening because of a REDCap immediate redirect.

If you look at the "new url" section (marked as line 128) it says it's fetching a GET request for `/Surveys/invite_participants.php?pid=13&participant_list=1` ... Cypress is waiting for the request response from initial click on "Survey Distribution Tools" ... from what I recall, REDCap gets a 302 direct from invite_participants.php and requests the `/Surveys/invite_participants.php?pid=13&participant_list=1` page.  This seems to be a problem for Cypress for whatever reason.

You can test this theory by visiting in your browser: 
http://localhost:8080/redcap_v14.7.0/Surveys/invite_participants.php?pid=13

I think it redirects to:
http://localhost:8080/redcap_v14.7.0/Surveys/invite_participants.php?pid=13&participant_list=1

I'm not clear on why this is a problem for Cypress so unsure of a fix at this point.

**Comment by aldefouw** [comment]
@mmcev106  & @alewis64  

Okay ... so I was completely wrong about the redirect.  That was a red herring.

Instead, I think it's related to the fact that a survey is not being enabled that should be:
![Screenshot 2024-11-20 at 1 58 35 PM](https://github.com/user-attachments/assets/d75be42a-6b91-4ab3-9d93-594a46899171)

In the Feature Test, it is looking for 
` When I select '"Consent" - Event 1 (Arm 1: Arm 1)' on the dropdown field labeled "Participant List"`

We should therefore see that as an option ... but we do not.  

I think this is some kind of issue related to REDcap not enabling the survey that is defined in the Project XML file.

If you look [here](https://github.com/4bbakers/redcap_rsvc/blob/v14.7.0/Files/cdisc_files/Project_1.xml#L60-L62) you will see that the Project_1.xml seems to define the survey.  

It seems that the fix is to fix the CDISC XML file.  

I ran a test on this XML file and the whole feature test worked when I used it in place of the existing Project_1.xml:
https://raw.githubusercontent.com/aldefouw/redcap_rsvc/refs/heads/v14.7.0/Files/cdisc_files/Fixed_Project.xml

I am unsure if we should outright replace the Project_1.xml file or not.  

Headed into a meeting but feel free to respond in this thread and I will respond when I can!

**Comment by mmcev106** [comment]
@alewis64, may I recruit you to merge the latest from 4bbakes/v14.7.0 into your branch and try again?  I'm not sure we've covered how to do that, so feel free to ask.

**Comment by alewis64** [comment]
@mmcev106 everything looks good and passes as expected.

**Comment by mmcev106** [comment]
Reopening as this fails for me.  I'm not immediately sure why Adam L is seeing different behavior.  I will investigate.

**Comment by mmcev106** [comment]
![image](https://github.com/user-attachments/assets/e5b1b054-a003-4fd0-99e9-b9cf73aaff8d)

**Comment by mmcev106** [comment]
Adam L pointed out that I was accidentally running the wrong test 🤦.  This one is indeed resolved!
