### ISSUE TITLE
B.3.15.1100. - Survey Response Tracking

### ISSUE THREAD

**Issue by aldefouw** [4bbakers/redcap_rsvc#37]
Feature: [B.3.15.1100. - Survey Response Tracking](https://github.com/4bbakers/redcap_rsvc/tree/v14.7.0/./Feature%20Tests/B/Direct%20Data%20Entry%20-%20Survey_15/B.3.15.1100.%20-%20Survey%20Response%20Tracking.feature)

**Comment by mmcev106** [comment]
@alewis64, I unassigned @aldefouw because I am trying to take point on as many of these as possible, and only raise questions to him if I get stuck.  @aldefouw, with that said, feel free to hop in on anything if/when you have the bandwidth and interest!

**Comment by aldefouw** [comment]
@mmcev106 @alewis64 - Please see the PR (Update Project_1.xml) referenced above this comment.  I think the PR will fix some of the issues in this feature test but likely not all.

**Comment by mmcev106** [comment]
@alewis64, I believe [this PR](https://github.com/4bbakers/redcap_rsvc/pull/143) should have fixed this. May I recruit you to merge the latest from 4bbakes/v14.7.0 into your branch and try again?  I'm not sure we covered how to do that, so feel free to ask.

**Comment by alewis64** [comment]
@mmcev106 it seems that that the setup steps below are no longer working. I also tested this on B.3.15.0800 which passed in the last version and is no longer passing in 14.7.0.

#SETUP_PRODUCTION
    When I click on the link labeled "Project Setup"
    And I click on the button labeled "Move project to production"
    And I click on the radio labeled "Keep ALL data saved so far" in the dialog box
    And I click on the button labeled "YES, Move to Production Status" in the dialog box to request a change in project status
    Then I should see Project status: "Production"
    
    
[localhost-1733513570865.log](https://github.com/user-attachments/files/18042903/localhost-1733513570865.log)

**Comment by mmcev106** [comment]
@alewis64, those steps seem to be working consistently on my local.  I saw them break on the call with you just now, but I was a little unclear on what was happening.  As I think about it more, I wonder if our automation is thinking "YES, Move to Production Status" is not being clicked successfully, even though it actually is.  In any case, let me know if you end up stuck on it.

**Comment by alewis64** [comment]
@mmcev106 I was able to make some progress. On line 45 we say "And I click on the link labeled "Leave without saving changes" in the dialog box", it appears this dialog box isn't appearing in version 14.7.0 on my local as it should. I can comment this line out and it processes appropriately. 

Here is an example of the dialog box that should appear. 
![Image](https://github.com/user-attachments/assets/9695da81-e719-4196-8ad9-3fbfe0ba7d10)

**Comment by mmcev106** [comment]
To wrap up the discussion here, @alewis64 discovered that this was already solved in another location by commenting this step and adding comment describing why this can currently only be tested manually.  See this PR for details:

https://github.com/4bbakers/redcap_rsvc/pull/157
