### ISSUE TITLE
B.2.6.400 - Creating Copying Deleting Roles

### ISSUE THREAD

**Issue by aldefouw** [4bbakers/redcap_rsvc#42]
Feature: [B.2.6.400 - Creating Copying Deleting Roles](https://github.com/4bbakers/redcap_rsvc/tree/v14.7.0/./Feature%20Tests/B/Assign%20User%20Rights_6/B.2.6.400%20-%20Creating%20Copying%20Deleting%20Roles.feature)

**Comment by mmcev106** [comment]
@MintooXavier, I really appreciate you going back through and closing these!  I had it on my list to review everything "In Progress" with recently merged PRs in mind.
