### ISSUE TITLE
B.3.16.0205. - Create & Modify Records

### ISSUE THREAD

**Issue by aldefouw** [4bbakers/redcap_rsvc#45]
Feature: [B.3.16.0205. - Create & Modify Records](https://github.com/4bbakers/redcap_rsvc/tree/v14.7.0/./Feature%20Tests/B/Data%20Import_16/B.3.16.0205.%20-%20Create%20&%20Modify%20Records.feature)

**Comment by alewis64** [comment]
Hey Mark i am seeing the same issues on this test as i did on this one https://github.com/orgs/vanderbilt-redcap/projects/2/views/1?pane=issue&itemId=86430962&issue=4bbakers%7Credcap_rsvc%7C44

It looks like whenever this line ( When I click on the link labeled "Data Import Tool") of Gherkin is used the same error shows up.
![Image](https://github.com/user-attachments/assets/1e646a58-910c-4af1-b44f-15b8a6679d13)

**Comment by mmcev106** [comment]
@alewis64, can you try the steps in [this comment](https://github.com/4bbakers/redcap_rsvc/issues/54#issuecomment-2549072678) and report back on this feature as well?

**Comment by alewis64** [comment]
@mmcev106 I don't know what the syntax for these sup dropdowns within the data import section needs to be. There are three different options and I don't see any other test that uses any of them. 
![Image](https://github.com/user-attachments/assets/51bd3bb0-5069-4337-b323-6952a1886bf4)
