### ISSUE TITLE
B.3.16.0400. - Field Validation

### ISSUE THREAD

**Issue by aldefouw** [4bbakers/redcap_rsvc#47]
Feature: [B.3.16.0400. - Field Validation](https://github.com/4bbakers/redcap_rsvc/tree/v14.7.0/./Feature%20Tests/B/Data%20Import_16/B.3.16.0400.%20-%20Field%20Validation.feature)

**Comment by mmcev106** [comment]
@schatto1, I believe @ellisthomas has a fix for this already.  I am reassigning it to him.  Hopefully you haven't looked at it in depth yet.
