### ISSUE TITLE
B.3.16.1100. - Change with edit access

### ISSUE THREAD

**Issue by aldefouw** [4bbakers/redcap_rsvc#54]
Feature: [B.3.16.1100. - Change with edit access](https://github.com/4bbakers/redcap_rsvc/tree/v14.7.0/./Feature%20Tests/B/Data%20Import_16/B.3.16.1100.%20-%20Change%20with%20edit%20access.feature)

**Comment by alewis64** [comment]
@mmcev106 I think I completed the changes for this test and submitted a pull request.

**Comment by alewis64** [comment]
The line "And I Upload a "csv......" is causing the script to fail. Image of what REDCap shows when it fails attached. 
>  ##ACTION: Import data
>         When I click on the link labeled "Data Import Tool"
>         And I upload a "csv" format file located at "import_files/B.3.16.2000.100data.csv", by clicking the button near "Upload your CSV file:" to browse for the file, and clicking the button labeled "Upload" to upload the file
>         And I click the button labeled "Upload File"

![Image](https://github.com/user-attachments/assets/23298224-9f8d-48b4-8f4f-96a981242e5e)

**Comment by mmcev106** [comment]
@alewis64, I've unassign you for now since this is on my plate to look into.

**Comment by mmcev106** [comment]
From @aldefouw:

> We might want to script it on the docker-compose.yml if possible (not sure about cross OS compatibility), but it looks pretty likely that the host machine's permissions on volume mounts via Docker are what is important.  In other words, you might need to set .../tmp/ to be more permissive on your host machine to make that folder writable. 
>  
> Evidence was found of this in the CircleCI pipeline too:
> https://github.com/aldefouw/redcap_cypress/blob/master/.circleci/config.yml#L59-L60
>  
> (777 seems way wrong to be honest ... maybe there is a less permissive combination we can use.  However, I do remember trying to make it less permissive - like 775 - and it failed to write, which doesn't make sense but since we're in a test environment I didn't waste too much time digging in.)
>

**Comment by aldefouw** [comment]
@mmcev106

One troubleshooting idea for the error in your screenshot is to run this: 
`docker exec -it redcap_docker-app-1 ls -la /var/www/html | grep temp`

That will tell you what the folder permissions are for /temp/.  For me, the folder is owned by root and is writable and readable by the folder owner.

If you need to adjust the permissions, you can do so through interactive terminal like you'd do on any machine:
`docker exec -it redcap_docker-app-1 /bin/bash`

It's hard for me to say if there is a fix we can write that would 100% fix this on every possible developer machine.  From what I've read, Docker runs slightly differently on Linux versus Mac and Windows.  It runs Natively on Windows whereas there is a translation of permissions for Mac and (especially for) Windows.

**Comment by mmcev106** [comment]
@alewis64, I've attempted to resolve this permanently for everyone via [this PR](https://github.com/aldefouw/redcap_docker/pull/2).  May I recruit you to do the following?

- Close out of cypress if you have it open
- Navigate to the `redcap_cypress_docker` dir on the command line
- Run `git pull` and verify that you see message about updating to `87ff6dc`
- Run `./run.sh`, run this feature, and let me know if the temp dir writability error is gone

**Comment by alewis64** [comment]
@mmcev106 when i followed the steps above I received this error when testing.  
![image](https://github.com/user-attachments/assets/0287af42-70a2-424e-943e-2f20d7c8c114)

**Comment by mmcev106** [comment]
@alewis64, I [have a fix for this](https://github.com/aldefouw/redcap_docker/pull/3).  I'll let you know once it's approved & merged.

**Comment by mmcev106** [comment]
@alewis64, the fix has been merged!  I believe these steps should resolve it for you.  Let me know if not, or if you want to go through the steps together on a call:
- Close out of cypress if you have it open
- Navigate to the `redcap_docker` dir on the command line
- Run `git checkout main`
- Run `git pull` and verify that you see message about updating to `e5db2d8`
- Run `docker compose up -d --build`
- Run `cd ..` to go to the `redcap_cypress_docker` dir
- Run `./run.sh`, try this feature again, and let me know if the temp dir writability error is gone

**Comment by alewis64** [comment]
@mmcev106 the fix was able to get me past the  directory error. It seems the file trying to be imported is missing the appropriate event column which is required for a longitudinal project. 
![image](https://github.com/user-attachments/assets/9355a612-a96b-4061-9bb5-efb69b9e50a9)

**Comment by mmcev106** [comment]
@alewis64, it looks like this step is trying to upload a file named `import_files/B.3.16.2000.100data.csv`, which doesn't actually exist.  Do you know if we could utilize one of the existing files in `import_files` to accomplish the goals in this feature?  Perhaps one of the ones referenced in the other `B.3.16` features?
