### ISSUE TITLE
B.3.16.1300_DataImport_Dag.csv

### ISSUE THREAD

**Issue by aldefouw** [4bbakers/redcap_rsvc#56]
Feature: [B.3.16.1300_DataImport_Dag.csv](https://github.com/4bbakers/redcap_rsvc/tree/v14.7.0/./Feature%20Tests/B/Data%20Import_16/B.3.16.1300.%20-%20Data%20Import%20-%20DAGs.feature%20./Files/import_files/B.3.16.1300_DataImport_Rows.csv%20./Files/import_files/B.3.16.1300_DataImport_Dag.csv)

**Comment by mmcev106** [comment]
@ellisthomas, I know you already fixed this, but it looks like you forgot to assign it to yourself.  I'm assigning you retroactively so you get credit for fixing it 😊.
