### ISSUE TITLE
B.3.16.2200. - DAG restriction

### ISSUE THREAD

**Issue by aldefouw** [4bbakers/redcap_rsvc#64]
Feature: [B.3.16.2200. - DAG restriction](https://github.com/4bbakers/redcap_rsvc/tree/v14.7.0/./Feature%20Tests/B/Data%20Import_16/B.3.16.2200.%20-%20DAG%20restriction.feature)

**Comment by mmcev106** [comment]
@4bbakers, do you have a copy of a `B.3.16.2200_DataImport_Dag.csv` file somewhere?

**Comment by mmcev106** [comment]
I got the file from Bosler.  Solved by #178
