### ISSUE TITLE
B.4.20.0300. - Instrument Behavior

### ISSUE THREAD

**Issue by aldefouw** [4bbakers/redcap_rsvc#65]
Feature: [B.4.20.0300. - Instrument Behavior](https://github.com/4bbakers/redcap_rsvc/tree/v14.7.0/./Feature%20Tests/B/Draft%20Mode_20/B.4.20.0300.%20-%20Instrument%20Behavior.feature)

**Comment by mmcev106** [comment]
Will be fixed once https://github.com/aldefouw/rctf/pull/9 is merged
