### ISSUE TITLE
B.4.20.0400. - Draft Mode Summary

### ISSUE THREAD

**Issue by aldefouw** [4bbakers/redcap_rsvc#66]
Feature: [B.4.20.0400. - Draft Mode Summary](https://github.com/4bbakers/redcap_rsvc/tree/v14.7.0/./Feature%20Tests/B/Draft%20Mode_20/B.4.20.0400.%20-%20Draft%20Mode%20Summary.feature)

**Comment by mmcev106** [comment]
Will be fixed once https://github.com/aldefouw/rctf/pull/9 is merged
