### ISSUE TITLE
B.4.20.0800. - Draft warning

### ISSUE THREAD

**Issue by aldefouw** [4bbakers/redcap_rsvc#70]
Feature: [B.4.20.0800. - Draft warning](https://github.com/4bbakers/redcap_rsvc/tree/v14.7.0/./Feature%20Tests/B/Draft%20Mode_20/B.4.20.0800.%20-%20Draft%20warning.feature)

**Comment by mmcev106** [comment]
Will be fixed once https://github.com/aldefouw/rctf/pull/9 is merged
