### ISSUE TITLE
B.4.9.0100. - Branching Logic

### ISSUE THREAD

**Issue by aldefouw** [4bbakers/redcap_rsvc#78]
Feature: [B.4.9.0100. - Branching Logic](https://github.com/4bbakers/redcap_rsvc/tree/v14.7.0/./Feature%20Tests/B/Branching%20Logic_9/B.4.9.0100.%20-%20Branching%20Logic.feature)

**Comment by MintooXavier** [comment]
In the following step definition, replace 'Variable' with 'Field Name':

1.  
 * @module OnlineDesigner
 * @author Adam De Fouw <aldefouw@medicine.wisc.edu>
 * @example I (should )see {string} within the field with variable name {string}

2.
 * @module Interactions
 * @author Adam De Fouw <aldefouw@medicine.wisc.edu>
 * @example I click on the {onlineDesignerFieldIcons} {fileRepoIcons} {linkNames} {labeledExactly} {string} {saveButtonRouteMonitoring} {toDownloadFile} {baseElement}

**Comment by aldefouw** [comment]
@MintooXavier - thank you for identifying the changes to the selectors.  Really low on time but I did squeeze in this change before my 9am meeting today.

Here is the update (v1.0.101) of rctf that fixes the selectors in a backwards compatible fashion: 
https://github.com/aldefouw/rctf/commit/314cb171cdc0c344ca07c7afea3ab0188fd2a5ea

@mmcev106 - you can push the rctf version to v1.0.101 on redcap_cypress when ready.  I think we decided over email yesterday to merge v14.7.0 into master at some point.  I can accept that PR at some point.

**Comment by mmcev106** [comment]
@aldefouw, my `redcap-cypress` PR now includes rctf v1.0.101:

https://github.com/aldefouw/redcap_cypress/pull/197

Let me know if you'd like me to split that up for any reason.  It looks like this change caused one failing feature to begin succeeding in the cloud (and did not have unexpected side affects on any other tests):

![image](https://github.com/user-attachments/assets/085b6327-b437-4506-8a46-11d611ca48f2)

@MintooXavier, it looks the feature that began succeeding was NOT this one, since that branch does not contain changes from your PR.  I will test those shortly and report back.

**Comment by mmcev106** [comment]
@MintooXavier, I'm seeing [this error](https://cloud.cypress.io/projects/pvu79o/runs/1939/test-results/a61403a6-385b-49ec-acb6-a27c2125aa86?actions=%5B%5D&browsers=%5B%5D&groups=%5B%5D&isFlaky=%5B%5D&modificationDateRange=%7B%22startDate%22%3A%221970-01-01%22%2C%22endDate%22%3A%222038-01-19%22%7D&orderBy=EXECUTION_ORDER&oses=%5B%5D&specs=%5B%7B%22label%22%3A%22redcap_rsvc%2FFeature%20Tests%2FB%2FBranching%20Logic_9%2FB.4.9.0100.%20-%20Branching%20Logic.feature%22%2C%22value%22%3A%22%5B%5C%22448d1558-b0d4-4680-971c-b1db77476335%5C%22%5D%22%7D%5D&statuses=%5B%5D&testingTypesEnum=%5B%5D) when running this features against rctf v1.0.101.  Do you know why that might be?

**Comment by mmcev106** [comment]
@MintooXavier, this test is passing in [cypres run 1956](https://cloud.cypress.io/projects/pvu79o/runs/1956), which means one of Sumon's recent rctf PRs resolved the issue.  Closing...  Thanks for your help on this!

**Comment by aldefouw** [comment]
@mmcev106 - on my radar.  I'll let you know if I can identify anything.

**Comment by aldefouw** [comment]
@mmcev106 - Pushed v1.0.105 up to RCTF which adds in a command to wait for "Loading ...." to go away on that step definition.

I ran it twice and it passed each time:

1) [Individually](https://cloud.cypress.io/projects/pvu79o/runs/1963/specs)

2) [Full Test Suite Run](https://cloud.cypress.io/projects/pvu79o/runs/1964/test-results?actions=%5B%5D&browsers=%5B%5D&groups=%5B%5D&isFlaky=%5B%5D&modificationDateRange=%7B%22startDate%22%3A%221970-01-01%22%2C%22endDate%22%3A%222038-01-19%22%7D&orderBy=EXECUTION_ORDER&oses=%5B%5D&specs=%5B%7B%22label%22%3A%22redcap_rsvc%2FFeature%20Tests%2FB%2FBranching%20Logic_9%2FB.4.9.0100.%20-%20Branching%20Logic.feature%22%2C%22value%22%3A%22%5B%5C%2299e30c8f-396e-4b8c-af2c-dba8ea2d0ff1%5C%22%5D%22%7D%5D&statuses=%5B%5D&testingTypesEnum=%5B%5D)

Hopefully this kills the flakiness you were encountering.

**Comment by mmcev106** [comment]
@aldefouw, wonderful, thank you! I'll go ahead & close this.  I have a half working script to check results from cypress runs against what we expect, and should notice on the off chance that this starts failing again.

**Comment by 4bbakers** [comment]
We need to add a scenerio for uploading data dictionary with branching logic.  

1. Download dictionary
2. Add branching logic to field
3. Upload dictionary
4. Verify branching logic is working
5. Check log :) 

Or something like this.
Let me know once this is complete so I can add the scenerio to the B.4.9.0100.'s documentation.

**Comment by alewis64** [comment]
@4bbakers The new scenario Scenario: B.4.9.0100.200 Branching Logic via Data Dictionary Upload has been added to B.4.9.0100. The scripting is lines 148-189. Let me know if you would like me to make any changes.
