### ISSUE TITLE
B.5.21.0100. - Export PHI

### ISSUE THREAD

**Issue by aldefouw** [4bbakers/redcap_rsvc#79]
Feature: [B.5.21.0100. - Export PHI](https://github.com/4bbakers/redcap_rsvc/tree/v14.7.0/./Feature%20Tests/B/Export%20Data_21/B.5.21.0100.%20-%20Export%20PHI.feature)

**Comment by alewis64** [comment]
@mmcev106 I just submitted a pull request for this one.

**Comment by mmcev106** [comment]
@alewis64, I'm seeing this passing in [cypress run 1956](https://cloud.cypress.io/projects/pvu79o/runs/1956)!  I ended up merging your changes for this feature from #160 instead of your PR (#161) since one of the other features in that PR is failing.  Closing!
