### ISSUE TITLE
B.5.21.0200. - Export Data to External Format

### ISSUE THREAD

**Issue by aldefouw** [4bbakers/redcap_rsvc#80]
Feature: [B.5.21.0200. - Export Data to External Format](https://github.com/4bbakers/redcap_rsvc/tree/v14.7.0/./Feature%20Tests/B/Export%20Data_21/B.5.21.0200.%20-%20Export%20Data%20to%20External%20Format.feature)

**Comment by ellisthomas** [comment]
@mmcev106 Test PASSES no changes were needed.

**Comment by mmcev106** [comment]
@ellisthomas, thanks for letting me know!  I have confirmed that this is also passing on the latest cloud run.  I suspect it was fixed by one of our recent rctf changes.
