### ISSUE TITLE
B.5.21.0400. - Export Specific Forms

### ISSUE THREAD

**Issue by aldefouw** [4bbakers/redcap_rsvc#82]
Feature: [B.5.21.0400. - Export Specific Forms](https://github.com/4bbakers/redcap_rsvc/tree/v14.7.0/./Feature%20Tests/B/Export%20Data_21/B.5.21.0400.%20-%20Export%20Specific%20Forms.feature)

**Comment by mmcev106** [comment]
Already working (perhaps fixed by a recent rctf change)
