### ISSUE TITLE
B.6.4.1400. - Repeating Surveys

### ISSUE THREAD

**Issue by aldefouw** [4bbakers/redcap_rsvc#85]
Feature: [B.6.4.1400. - Repeating Surveys](https://github.com/4bbakers/redcap_rsvc/tree/v14.7.0/./Feature%20Tests/B/Project%20Setup_4/B.6.4.1400.%20-%20Repeating%20Surveys.feature)

**Comment by MintooXavier** [comment]
Working fine

**Comment by mmcev106** [comment]
I can also confirm this is working fine.  Closing...
