### ISSUE TITLE
B.6.7.0700. - Field Textbox

### ISSUE THREAD

**Issue by aldefouw** [4bbakers/redcap_rsvc#87]
Feature: [B.6.7.0700. - Field Textbox](https://github.com/4bbakers/redcap_rsvc/tree/v14.7.0/./Feature%20Tests/B/Online%20Designer_7/B.6.7.0700.%20-%20Field%20Textbox.feature)

**Comment by mmcev106** [comment]
Fixed via https://github.com/4bbakers/redcap_rsvc/pull/160
