### ISSUE TITLE
B.6.7.1000. - Field Multiple Choice

### ISSUE THREAD

**Issue by aldefouw** [4bbakers/redcap_rsvc#88]
Feature: [B.6.7.1000. - Field Multiple Choice](https://github.com/4bbakers/redcap_rsvc/tree/v14.7.0/./Feature%20Tests/B/Online%20Designer_7/B.6.7.1000.%20-%20Field%20Multiple%20Choice.feature)

**Comment by mmcev106** [comment]
Will be fixed once https://github.com/aldefouw/rctf/pull/9 is merged
