### ISSUE TITLE
B.6.7.1200. - Field Checkbox

### ISSUE THREAD

**Issue by aldefouw** [4bbakers/redcap_rsvc#90]
Feature: [B.6.7.1200. - Field Checkbox](https://github.com/4bbakers/redcap_rsvc/tree/v14.7.0/./Feature%20Tests/B/Online%20Designer_7/B.6.7.1200.%20-%20Field%20Checkbox.feature)

**Comment by mmcev106** [comment]
Will be resolved by https://github.com/4bbakers/redcap_rsvc/pull/177/files
