### ISSUE TITLE
B.6.7.1800. - Required Fields

### ISSUE THREAD

**Issue by aldefouw** [4bbakers/redcap_rsvc#91]
Feature: [B.6.7.1800. - Required Fields](https://github.com/4bbakers/redcap_rsvc/tree/v14.7.0/./Feature%20Tests/B/Online%20Designer_7/B.6.7.1800.%20-%20Required%20Fields.feature)

**Comment by ellisthomas** [comment]
@mmcev106 I will have to get in an take a look. I honestly can't rememeber. I

**Comment by ellisthomas** [comment]
> [@mmcev106](https://github.com/mmcev106) I will have to get in an take a look. I honestly can't rememeber.

This test has passed!

**Comment by mmcev106** [comment]
@ellisthomas, wonderful!  Moving to "Done".
